#!/usr/bin/env bash

# upgrade all macports while doing some house cleaning
# https://stackoverflow.com/a/7491014

# ==============================================================
# ======================= PORT SPECIFIC ========================
# ==============================================================
#
readonly PORTS="kops qt5-qttools libpsl zig speedtest-cli"
# these ports change often and won't be fixed soon
readonly SKIP_PORT_MD5=(qt5-qttools libpsl)

readonly LLVM_VERSION=22
readonly PY_VERSION=3.14
readonly PY_VERS_NODOT="${PY_VERSION//./}"

function handle_kops()
{
    portfile="${1}"
    shift
    handle_depends "${portfile}" mv kubectl1.32 kubectl1.35
}

function handle_qt5-qttools()
{
    portfile="${1}"
    shift
    set_param "${portfile}" llvm_version "${LLVM_VERSION}"
}

function handle_libpsl()
{
    portfile="${1}"
    shift
    set_param "${portfile}" py_ver "${PY_VERS_NODOT}"
}

function handle_speedtest-cli()
{
    portfile="${1}"
    shift
    set_param "${portfile}" python.default_version "${PY_VERS_NODOT}"
}

function handle_zig()
{
    portfile="${1}"
    shift
    set_param "${portfile}" llvm_version "${LLVM_VERSION}"
}
# ==============================================================
# ==============================================================
# ==============================================================

if [[ -n "${DEBUG}" ]]; then
    exec 5> /tmp/bash_debug_output.txt
    BASH_XTRACEFD="5"
    PS4='$LINENO: '
    set -x -T
fi

# freezeports_hashes file format:
# $ cat ~/.local/share/macports/freezeports_hashes
# dd94e2d3e7eed7f7bfcc1b3f0afb3835    google-cloud-sdk
# 43bf28556dfc9b534d5cc4fd08662a30    qt5-qttools
FREEZEPORTS_HASHES="${XDG_DATA_DIR:-${HOME}/.local/share/macports/freezeports_hashes}"
readonly FREEZEPORTS_HASHES

function usage()
{
    cat << EOF
Usage: ${0##*/} [OPTION]...
Options: -h, --help: show this help dialog
         --no-selfupdate: run \`port selfupdate\`
EOF
}

function set_param()
{
    portfile="${1}"
    shift
    param="${1}"
    shift
    value="${*}"
    shift
    (grep -qE "^(\s*set )?${param}(\s+)" "${portfile}" \
        && sed -i -E "s/^(\s*set )?${param}(\s+).*$/\1${param}\2${value}/g" "${portfile}") \
        || echo -e "\n${param}   ${value}" >> "${portfile}"
}

function handle_depends()
{
    portfile="${1}"
    shift
    action="${1}"
    shift
    value="${1}"
    shift

    case "${action}" in
        add)
            printf 'IMPLEMENT ME!\n'
            exit 1
            ;;
        rm)
            sed -i -E "s/\bport:${value}\b//g" "${portfile}"
            ;;
        mv)
            newval="${1}"
            shift
            sed -i -E "s/\bport:${value}\b/port:${newval}/g" "${portfile}"
            ;;
        *)
            printf "Unknown action %s\n" "${action}"
            exit 1
            ;;
    esac
}

function readhash()
{
    local portname="${1}"
    shift

    # https://unix.stackexchange.com/a/462089
    declare -n hashes="freezeports_md5"
    # shellcheck disable=SC2034
    hashes["${portname}"]="$(awk "/${portname}/ {print \$1}" "${FREEZEPORTS_HASHES}")"
}

function macports_localchanges()
{
    # we store the hash in $FREEZEPORTS_HASHES file
    # If the stored hash does not match the computed hash, that means the portfile
    # has changed and we should reapply our changes manually and potentially
    # update the handle_portname function in thiis script as well
    # If the stored hash does match the computed hash, the handle_portname
    # function will handle everything for us
    declare -A freezeports_md5=()
    for portname in ${PORTS}; do
        readhash "${portname}"
        portfile="$(port file "${portname}")"
        portfile_md5_actual="$(md5sum "${portfile}" | awk '{print $1}')"
        portfile_md5_expected="${freezeports_md5[${portname}]}"
        if [[ "${portfile_md5_actual}" != "${portfile_md5_expected}" \
            && ! "${SKIP_PORT_MD5[*]}" =~ (^|[[:space:]])${portname}([[:space:]]|$) ]]; then
            tmpfile=$(mktemp)
            echo "${portname} updated!"
            vim_cmd_payload="$(md5sum "${portfile}" | awk "{print \$1  \"\t${portname}\"}")"
            echo -e "\"m\tLINE\t0\n\t${vim_cmd_payload}" > "${tmpfile}"
            vim -i "${tmpfile}" -O "${FREEZEPORTS_HASHES}" "${portfile}"
            rm "${tmpfile}"
        else
            # https://stackoverflow.com/a/33387433
            handle_"${portname}" "${portfile}"
        fi
    done
}

function port_reclaim_wrapper()
{
    expect << 'EOF'
spawn port reclaim -N
expect {
  "\[l\]ist/\[d\]elete/\[K\]eep:" { send "d\r"; exp_continue }
  "delete all the build directories?" { send "y\r"; exp_continue }
  "delete everything under the ccache directory?" { send "n\r"; exp_continue }
  "Would you like to delete them?" { send "y\r"; exp_continue }
  eof
}
EOF
}

function postinstall_tasks()
{
    # the default gitconfig shipped with macports overrides my credential helper
    # git checks in /opt/local/etc/gitconfig, ~/.gitconfig and
    # ~/.config/git/config by default, but if /opt/local/etc/gitconfig exists,
    # it doesn't read ~/.config/git/config. Let's remove it
    rm -f /opt/local/etc/gitconfig

    if port installed keychain|grep -q 'The following ports are currently installed'; then
        # shellcheck disable=SC2016
        port contents keychain \
            | grep /opt/local/bin \
            | xargs sed -i -E 's#^keydir="\$\{HOME\}/.keychain"$#keydir="\${HOME}/.local/share/ssh-agent"#'
    fi
}

function duplicate_ports_installed()
{
    port installed \
        | awk '{print $1}' \
        | sort \
        | uniq -c \
        |sort -rn \
        | awk '$1 >= "2" {print $0}'
}

function port_select_review()
{
    # go through each line. Each option ($3+) is added to an array in the first
    # loop
    # In the second loop, check if the selected option ($2) is one of the valid
    # options => in the array
    port select --summary \
        | tail -n +3 \
        | awk '{
            for (col=3; col <= NF; col++) {
                if ($col != "none") {
                    arr[$col]=true
                }
            }
            if ($2 in arr == 0) {
                printf "%s -> %s\toptions: ", $1, $2
                for (select in arr) {
                    printf "%s ", select
                }; printf "\n"
            }
            delete arr
        }' \
        | column -t
}

function main()
{
    run_port_selfupdate=true

    while getopts "h-:" opt; do
        case "${opt}" in
            h) # help message
                usage
                exit 0
                ;;
            -)
                case "${OPTARG}" in
                    help)
                        usage
                        exit 0
                        ;;
                    no-selfupdate)
                        run_port_selfupdate=false
                        ;;
                    *)
                        printf "Unknown option, exiting now\n" >&2
                        exit 1
                        ;;
                esac
                ;;
            *)
                printf "Unknown option, exiting now\n" >&2
                exit 1
                ;;
        esac
    done
    if "${run_port_selfupdate}"; then
        port selfupdate
    fi
    macports_localchanges
    port upgrade outdated
    port uninstall leaves inactive rleaves || true
    port_reclaim_wrapper
    port_cutleaves
    postinstall_tasks
    duplicate_ports_installed
    port_select_review
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    set -e -u -o pipefail
    main "$@"
fi
