#!/usr/bin/env bash

# Auto-kill+restart spotify when it tries to play an ad. This script will keep
# running in the background and will automatically stop running when spotify
# stops running
#
# https://github.com/Jugran/spotify-ad-killer/blob/master/spotify-ad-killer.sh

if [ -n "${DEBUG}" ]; then
    exec 5> /tmp/bash_debug_output.txt
    BASH_XTRACEFD="5"
    PS4='$LINENO: '
    set -x -T
fi

# Know which signal is caught
# man 7 signal
for i in {1..31}; do
    # ignore sigchld and sigwinch
    # shellcheck disable=SC2064
    if [[ ${i} -ne 20 && ${i} -ne 28 ]]; then
        trap "bell -m 'signal ${i} caught!'" "${i}"
    fi
done

function usage()
{
    cat << EOF
Usage: ${0##*/}" [OPTION]...
Options: -h, --help: show this help dialog
         -v, --volume: set application-specific volume (0=silent, 100=max/default)
EOF
}

function monitor_and_skip_ads()
{
    volume="${1}"; shift
    old_track_id=""

    while is_spotify_running; do
        track_id="$(timeout 1 osascript -e 'tell application "spotify" to id of current track' || echo "")"
        if [[ ${track_id} =~ "spotify:ad:" || (${track_id} == "" && $(is_spotify_running)) ]]; then
            pkill -9 -i spotify
            # pkill -9 leaves the Apple Events subsystem in a broken state.
            # Poll until osascript is functional again before proceeding.
            until osascript -e 'return 0' &>/dev/null 2>&1; do sleep 0.5; done
            spotify_launchnplay
            track_id="$(timeout 1 osascript -e 'tell application "spotify" to id of current track' || echo "")"
            if [[ ${track_id} =~ "spotify:ad:" || ${track_id} == "" || ${track_id} == "${old_track_id}" ]]; then
                osascript -e 'tell application "spotify" to next track'
            fi
            spotify_set_volume "${volume}"
            osascript -e 'tell application "spotify" to play'
            sleep 5
        fi
        old_track_id="${track_id}"
        sleep 1
    done
    bell -m "no spotify running; audio_ads_adios exiting now"
}

function spotify_set_volume()
{
    volume="${1}"; shift

    osascript -e "tell application \"spotify\" to set sound volume to ${volume}"
}

function process_supervisor()
{
    volume="${1}"; shift

    while is_spotify_running; do
        monitor_and_skip_ads "${volume}" &
        wait "$(jobs -p)"
    done
}

function is_spotify_running()
{
    test "$(pgrep -i spotify)" != ""
}

function is_audio_adblocker_running()
{
    # greater than 2: one for the self, and one for the fork
    test "$(pgrep -alf 'bash' | grep -c audio_ads_adios)" -gt 2
}

function spotify_launchnplay()
{
    local foreground_app
    foreground_app="$(osascript \
        -e 'tell application "System Events" to name of first application process whose frontmost is true and name is not "MSTeams" and name is not "studio" and name is not "idea"' \
        2>/dev/null || echo "")"

    osascript -e 'tell application "Spotify" to launch'
    sleep 0.5

    if [[ -n "${foreground_app}" && "${foreground_app}" != "Spotify" ]]; then
        osascript -e "tell application \"${foreground_app}\" to activate"
    fi

    sleep 2
    osascript -e 'tell application "spotify" to play'
}

function main()
{
    local volume=100

    while getopts "hv:-:" opt; do
        case ${opt} in
            h) # help message
                usage
                exit 0
                ;;
            v)
                volume="${OPTARG}"; shift
                ;;
            -)
                case "${OPTARG}" in
                    help)
                        usage
                        exit 0
                        ;;
                    volume)
                        volume="${!OPTIND}"
                        OPTIND=$((OPTIND + 1))
                        ;;
                    *)
                        printf 'Unknown option, exiting now\n' >&2
                        exit 1
                        ;;
                esac
                ;;
            ?)
                printf 'Unknown option, exiting now\n' >&2
                exit 1
                ;;
        esac
    done
    shift $((OPTIND - 1))
    [[ ${1-} == '--' ]] && shift

    if ! is_spotify_running; then
        spotify_launchnplay
    fi
    spotify_set_volume "${volume}"

    if is_audio_adblocker_running; then
        printf "already running\n"
    else
        process_supervisor "${volume}" &
    fi
    exit 0
}

if [ "${BASH_SOURCE[0]}" == "$0" ]; then
    set -e -u -o pipefail
    main "$@"
fi
