#!/usr/bin/env bash

set -e -u
set -o pipefail

# write some cool doc here

function usage ()
{
    cat << EOF
Usage: $(basename $0) [OPTION]...
Options: --help, -h: show this help dialog
EOF
}

function main ()
{
    local device=foles

    while getopts "h-:" opt; do
        case ${opt} in
            h)  # help message
                usage
                exit 0
                ;;
            -)
                case "${OPTARG}" in
                    help)
                        usage
                        exit 0
                        ;;
                    hong)
                        device=nash
                        ;;
                    *)
                        printf 'Unknown option, exiting now\n' >&2
                        exit 1
                        ;;
                esac
                ;;
            ?)
                echo "Unknown option, exiting now" >&2
                exit 1
                ;;
        esac
    done
    shift $((OPTIND - 1))
    [[ "${1:-}" == '--' ]] && shift

    fastboot boot ~/Documents/android-personal/$device/magisk_patched.img
}

if [ "${BASH_SOURCE[0]}" == "$0" ]; then
    main "$@"
fi
