#!/usr/bin/env bash

function main ()
{
    tmpdir="$(mktemp -d)"
    tmprc="$(mktemp)"

    cat > "$tmprc" << EOF
PS1='\$ '
cd "$tmpdir"
EOF

    env - HOME="$tmpdir" TERM="$TERM" bash --noprofile --rcfile "$tmprc"
    rm -rf "$tmpdir" "$tmprc"
}

if [ "${BASH_SOURCE[0]}" == "$0" ]; then
    main "$@"
fi
