#!/usr/bin/env bash

# delete shitloads of temporary files or files polluting the homedir
#
# $ cleanup
# $ cleanup -b

if [ -n "${DEBUG}" ]; then
    exec 5> /tmp/bash_debug_output.txt
    BASH_XTRACEFD="5"
    PS4='$LINENO: '
    set -x -T
fi
set -e -u
set -o pipefail

function main()
{
    homedir_dirs=(
        .AbiSuite
        .Tribler
        .abrt
        .adobe
        .agdb
        .AMD
        .ansible
        .ansible_async
        .appletviewer
        .aptitude
        .aria2
        .assaultcube_v1.104
        .audacity-data
        .bash_sessions
        .cabal
        .cache
        .cargo
        .CFUserTextEncoding
        .cgobanrc
        .colima
        .config/abrt
        .config/asciinema
        .config/binwalk
        ".config/chromium/Default/Local Storage"
        .config/cinnamon-session
        .config/clipit
        .config/configstore
        .config/coc/extensions/coc-java-data
        .config/DjVuLibre
        .config/enchant
        .config/eog
        .config/evince
        .config/evolution
        .config/filezilla
        .config/gcloud
        .config/gconf
        .config/gedit
        .config/gnome-disk-utility
        .config/gnome-initial-setup-done
        .config/gnome-session
        .config/goa-1.0
        ".config/google-chrome/Default/Local Storage"
        .config/google-googletalkplugin
        .config/gtk-2.0
        .config/gtk-3.0
        .config/guvcview2
        .config/htop
        .config/ibus
        .config/imsettings
        .config/iTerm2
        .config/jgit
        .config/kazam
        .config/lftp
        .config/libreoffice
        .config/libvirt
        .config/menus
        .config/nautilus
        .config/neofetch
        .config/octave
        .config/procps
        .config/qvm-mru-filecopy
        .config/Skype
        .config/"spotify/User Data"
        .config/sqlitebrowser
        .config/totem
        .config/Thunar
        .config/tracker
        .config/viewnior
        .config/xarchiver
        .config/yelp
        .cinnamon
        .cups
        .dbus
        .ddd
        .designer
        .dlv
        .docker
        .dreamchess
        .DS_Store
        .dvdcss
        .eclipse
        .electron-gyp
        .elinks
        .emacs.d
        .erlang.cookie
        .evolution
        .fastboot
        .fontconfig
        .forever
        .freemind
        .gconfd
        .gdb_history
        .gegl-0.0
        .getdown
        .ghidra
        .gimp-2.8
        .git-credential-cache
        .gksu.lock
        .gnash
        .gnome
        .gnome2
        .gnome2_private
        .gnote
        .golly
        .googleearth
        .grip
        .gstreamer-0.10
        .gvfs
        .hawtjni
        .hedgewars
        .hex
        .icedtea
        .icons
        .isag.cfg
        .java
        .jupyter
        .keras
        .kde
        .kismet
        .lemminx
        .lftp
        .lima
        .links
        .links2
        .lldb
        .lnav
        .local/share/flatpak
        .local/share/gsettings-data-convert
        .local/share/gstreamer-1.0
        .local/share/gvfs-metadata
        .local/share/keyrings
        .local/share/lftp
        .local/share/nautilus
        .local/share/nvim
        .local/share/tracker
        .local/share/vlc
        .local/share/xorg
        .macports
        .macromedia
        .matlab
        .matplotlib
        .mc
        .mcop
        .mission-control
        .mplayer
        .muttator
        .mysqlsh
        .m2
        .nano
        .nautilus
        .nedit
        .nemo
        .node-gyp
        .npm
        .nv
        .nvimlog
        .nvm
        .octave_hist
        .oracle_jre_usage
        .osquery
        .p2
        .packer.d
        .parallel
        .pdfedit
        .pEp
        .pex
        .pip
        .pki
        .plotly
        .pulse
        .pylint.d
        .python27_compiled
        .python_history
        .quodlibet/dumps
        .qt
        .recently-used.xbel
        .redhat
        .repoconfig
        .scala_history
        .sqlite_history
        .sunstudio
        .stack
        .swiftpm
        .swt
        .task
        .terraform.d
        .texlive2020
        .texmf-var
        .themes
        .thumbnails
        .tmp
        .tooling
        .ts_node_repl_history
        .tuist
        .Trash
        .update-notifier
        .vidalia
        .w3m
        .wireshark
        .yarn
    )
    homedir_files=(
        .AndroidStudio2.0/config/options/feature.usage.statistics.xml
        .AndroidStudio2.0/config/options/statistics.application.usages.xml
        .AndroidStudio2.0/config/options/usage.statistics.xml
        .ICEauthority
        .aspell*
        .babel.json
        .config/QtProject.conf
        .config/Trolltech.conf
        .config/user-dirs.dirs
        .config/user-dirs.locale
        .cuda-gdbinit
        .DS_Store
        .emulator_console_auth_token
        .esd_auth
        .fixmyserver-homedir-write-test
        .fonts.conf
        .gnuplot_history
        .google-cookie
        .gtk-bookmarks
        .history
        .hivehistory
        .hphpd.history
        .hphpd.ini
        .imsettings.log
        .kotlinc_history
        .lesshst
        .mycli.log
        .myclirc
        .mysql_history
        .node_repl_history
        .npmrc
        .ocamldebug_history
        .ophcrackrc
        .pdbhistory
        .pEp_management.db
        .pEp_management.db-shm
        .pEp_management.db-wal
        .pspg_history
        .pulse-cookie
        .recently-used
        .rediscli_history
        .repo_.gitconfig.json
        .rnd
        .sack_shortcuts
        .scala_history
        .scm.sqlite
        .scuba_history
        .serfcli2
        .sqlite_history
        .sudo_as_admin_successful
        .tilp
        .v8flags*
        .vault-token
        .vim/.netrwhist
        .vimspector.log
        .viminfo
        .wget-hsts
        .xfce4-session.verbose-log*
        .xsession-errors*
        .xsettingsd
        .yarnrc
        .ypp_42
        .zcompdump
        .yaegi_history
    )
    tmpfiles=(
        com.apple.CoreSimulator.SimDevice.*
        com.apple.launchd.*
        fastzip-castree-uid-*
        gnash-cookies.*
        hhvm_*
        packman-fb-*
        par_preload_unpack.*
        par_unpack.*
        perf-*.map
        pymp-*
        scm-internal-stats*
        testpilot.*
        tmp*
        wmlock-*
        www-vmtouch-*
        www_vmtouch_db_cache.json
        com.apple.launchd.*
    )
    mac_library_caches_files=(
        Chromium
        CloudKit
        Cypress
        "Docker Desktop"
        Firefox
        GameKit
        GeoServices
        Google
        "Google Earth"
        JNA
        Jedi
        JetBrains
        KSCrash
        Mozilla
        Nuitka
        Passkit
        "Python Entry Points"
        RDFileSearch_crashesLog.plist
        SentryCrash
        SwiftLint
        "TurboTax 2023"
        WhatsApp.ShipIt
        Yarn
        aerc
        app.riftshare
        askpermissiond
        black
        ccache
        com.apple.AMPDevicesAgent
        com.apple.AMPLibraryAgent
        com.apple.AppStore
        com.apple.AppleMediaServices
        com.apple.AvatarKit
        com.apple.DictionaryServices
        com.apple.HomeKit
        com.apple.Music
        com.apple.NewDeviceOutreach
        com.apple.Spotlight
        com.apple.WalletSettingsExtension
        com.apple.accountsd
        com.apple.akd
        com.apple.amsaccountsd
        com.apple.amsengagementd
        com.apple.ap.adprivacyd
        com.apple.appstoreagent
        com.apple.assistant_cdmd
        com.apple.assistantd
        com.apple.automator.actionCache-bundleLocations.plist
        com.apple.automator.actionCache-system-standardLocations.plist
        com.apple.bookassetd
        com.apple.bookdatastored
        com.apple.businessservicesd
        com.apple.cache_delete
        com.apple.chrono
        com.apple.commerce
        com.apple.containermanagerd
        com.apple.ctcategories.service
        com.apple.dataaccess.dataaccessd
        com.apple.dt.Instruments
        com.apple.dt.Xcode
        com.apple.dt.xcodebuild
        com.apple.feedbacklogger
        com.apple.gamed
        com.apple.helpd
        com.apple.homed
        com.apple.iCloudNotificationAgent
        com.apple.iTunesCloud
        com.apple.ibtool
        com.apple.icloud.fmfd
        com.apple.itunescloudd
        com.apple.nbagent
        com.apple.nsservicescache.plist
        com.apple.nsurlsessiond
        com.apple.parsecd
        com.apple.passd
        com.apple.preferencepanes.usercache
        com.apple.proactive.eventtracker
        com.apple.python
        com.apple.remindd
        com.apple.siri.embeddedspeech
        com.apple.siriknowledged
        com.apple.sirittsd
        com.apple.storekitagent
        com.apple.systemsettings.menucache
        com.apple.tipsd
        com.apple.tiswitcher.cache
        com.apple.translationd
        com.figma.agent
        com.google.GoogleUpdater
        com.google.KeyStone
        com.google.SoftwareUpdate
        com.hnc.Discord.ShipIt
        com.intuit.turbotax.2023
        com.objective-see.KnockKnock
        com.objective-see.Netiquette
        com.objective-see.TaskExplorer
        com.objective-see.blockblock.helper
        com.objective-see.dnd.helper
        com.objective-see.lulu.app
        com.objective-see.oversight
        com.plausiblelabs.crashreporter.data
        com.postmanlabs.mac
        com.postmanlabs.mac.ShipIt
        com.sonymobile.Xperia-Companion
        com.spotify.client.helper
        docker-compose
        familycircled
        fanal
        gopls
        go-build
        icon-cache.kcache
        im.riot.app.ShipIt
        js-v8flags
        kdeconnect.daemon
        kdeconnect.sms
        lima
        main.kts.compiled.cache
        ms-playwright
        net.tunnelblick.tunnelblick
        node-gyp
        org.herf.FLux
        org.mozilla.crashreporter
        org.swift.swiftpm
        org.videolan.vlc
        org.webkit.Playwright
        org.whispersystems.signal-desktop.ShipIt
        pip
        rga
        staticcheck
        swift-package
        update-informer-rs
    )

    # separately to avoid any array issues
    #rm -rf $HOME/.android/!(avd)

    if [[ ${OSTYPE} =~ darwin ]]; then
        for osxcacheentry in "${mac_library_caches_files[@]}"; do
            rm -rf ~/Library/Caches/"${osxcacheentry}"
        done
        # OSX is lame
        test -d ~/.Trash && (/bin/chmod -N ~/.Trash || echo fuck mac)
    fi

    for d in "${homedir_dirs[@]}"; do
        rm -rf "$HOME/${d:?}"
    done
    for f in "${homedir_files[@]}"; do
        rm -f "$HOME/${f}"
    done
    for d in "${tmpfiles[@]}"; do
        # shellcheck disable=SC2086
        rm -rf /tmp/${d} 2> /dev/null
    done
    LOCATE=$([[ $(uname) == Darwin ]] && echo slocate || echo locate)
    # shellcheck disable=SC2046
    (${LOCATE} recently-used.xbel || echo) | xargs -r rm -f

    if [ -d ~/.mozilla ]; then
        firefox_cleanup
    fi

    # clean up all docker shit
    if [ -n "$(which docker 2> /dev/null)" ]; then
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /etc:/etc spotify/docker-gc 2> /dev/null || true
    fi
    if [ $# -eq 1 ] && [ "${1}" == "-b" ]; then
        bleachbit_func
    fi
    root_func
}

# firefox trash
function firefox_cleanup()
{
    cd ~/.mozilla 2> /dev/null
    rmdir extensions 2> /dev/null
    cd firefox 2> /dev/null
    for profile in *.default; do
        cd "${profile}"
        rm -rf startupCache Cache bookmarkbackups thumbnails OfflineCache thumbnails
        rm -f adblockplus/patterns-backup* adblockplus/cache.js chromeappstore.sqlite
        cd ..
    done
}

function bleachbit_func()
{
    if [ -n "$(which bleachbit 2> /dev/null)" ]; then
        bleachbit -c \
            adobe_reader.cache \
            adobe_reader.mru \
            adobe_reader.tmp \
            amsn.cache \
            amule.logs \
            amule.tmp \
            apt.autoclean \
            apt.autoremove \
            audacious.cache \
            audacious.log \
            audacious.mru \
            beagle.cache \
            beagle.index \
            beagle.logs \
            chromium.cache \
            chromium.cookies \
            chromium.dom \
            chromium.form_history \
            chromium.vacuum \
            d4x.history \
            deepscan.ds_store \
            deepscan.thumbs_db \
            deepscan.tmp \
            easytag.logs \
            elinks.history \
            emesene.cache \
            emesene.logs \
            epiphany.cache \
            epiphany.cookies \
            epiphany.passwords \
            epiphany.places \
            evolution.cache \
            exaile.cache \
            exaile.downloaded_podcasts \
            exaile.log \
            filezilla.mru \
            firefox.cache \
            firefox.crash_reports \
            firefox.dom \
            firefox.forms \
            firefox.vacuum \
            flash.cache \
            flash.cookies \
            gedit.recent_documents \
            gftp.cache \
            gftp.logs \
            gimp.tmp \
            gl-117.debug_logs \
            gnome.run \
            gnome.search_history \
            google_chrome.cache \
            google_chrome.cookies \
            google_chrome.dom \
            google_chrome.form_history \
            google_chrome.history \
            google_chrome.passwords \
            google_chrome.search_engines \
            google_chrome.session \
            google_chrome.vacuum \
            google_earth.temporary_files \
            google_toolbar.search_history \
            gpodder.cache \
            gpodder.vacuum \
            gwenview.recent_documents \
            hippo_opensim_viewer.cache \
            hippo_opensim_viewer.logs \
            java.cache \
            kde.cache \
            kde.recent_documents \
            kde.tmp \
            konqueror.cookies \
            konqueror.current_session \
            konqueror.url_history \
            libreoffice.cache \
            libreoffice.history \
            liferea.cache \
            liferea.cookies \
            liferea.vacuum \
            links2.history \
            midnightcommander.history \
            miro.cache \
            miro.logs \
            nautilus.history \
            nexuiz.cache \
            octave.history \
            openofficeorg.cache \
            openofficeorg.recent_documents \
            opera.cache \
            opera.cookies \
            opera.current_session \
            opera.dom \
            opera.download_history \
            opera.search_history \
            opera.url_history \
            pidgin.cache \
            pidgin.logs \
            realplayer.cookies \
            realplayer.history \
            realplayer.logs \
            recoll.index \
            rhythmbox.cache \
            screenlets.logs \
            seamonkey.cache \
            seamonkey.chat_logs \
            seamonkey.cookies \
            seamonkey.download_history \
            seamonkey.history \
            secondlife_viewer.Cache \
            secondlife_viewer.Logs \
            sqlite3.history \
            system.custom \
            system.desktop_entry \
            system.localizations \
            system.recent_documents \
            system.rotated_logs \
            system.trash \
            thumbnails.cache \
            thunderbird.cache \
            thunderbird.cookies \
            thunderbird.vacuum \
            tremulous.cache \
            vim.history \
            vlc.mru \
            vuze.backup_files \
            vuze.cache \
            vuze.logs \
            vuze.tmp \
            warzone2100.logs \
            wine.tmp \
            winetricks.temporary_files \
            x11.debug_logs \
            xine.cache \
            yum.clean_all \
            yum.vacuum
    else
        # shellcheck disable=SC2016
        echo 'bleachbit not found in $PATH' >&2
    fi
}

function root_func()
{
    if [ $EUID == 0 ]; then
        echo LoL
        #        rm -r "/usr/share/locale/{[a-dg-z]*,e!(n),fr[a-z_@]*}"
        #        rm -r /usr/share/man/[a-no-z]*
    fi
}

if [ "${BASH_SOURCE[0]}" == "$0" ]; then
    main "$@"
fi
