#!/usr/bin/env bash

# delete shitloads of temporary files or files polluting the homedir
#
# $ cleanup
# $ cleanup -b

function main ()
{
    homedir_dirs=(
        .AbiSuite
        .Tribler
        .abrt
        .adobe
        .agdb
        .AMD
        .ansible
        .ansible_async
        .appletviewer
        .aptitude
        .aria2
        .assaultcube_v1.104
        .audacity-data
        .cache
        .CFUserTextEncoding
        .cgobanrc
        .cinnamon
        .cups
        .dbus
        .ddd
        .dreamchess
        .DS_Store
        .docker
        .dvdcss
        .eclipse
        .elinks
        .emacs.d
        .evolution
        .fontconfig
        .forever
        .freemind
        .gconfd
        .gdb_history
        .gegl-0.0
        .getdown
        .gimp-2.8
        .git-credential-cache
        .gksu.lock
        .gnash
        .gnome
        .gnome2
        .gnome2_private
        .gnote
        .golly
        .googleearth
        .gstreamer-0.10
        .gvfs
        .hedgewars
        .icedtea
        .icons
        .isag.cfg
        .java
        .jupyter
        .kde
        .lftp
        .links
        .links2
        .lldb
        .lnav
        .macports
        .macromedia
        .matlab
        .matplotlib
        .mc
        .mcop
        .mission-control
        .mplayer
        .muttator
        .mysqlsh
        .m2
        .nano
        .nautilus
        .nedit
        .nemo
        .node-gyp
        .npm
        .nv
        .nvimlog
        .octave_hist
        .oracle_jre_usage
        .osquery
        .packer.d
        .parallel
        .pdfedit
        .pEp
        .pex
        .pip
        .pki
        .plotly
        .pulse
        .pylint.d
        .python27_compiled
        .python_history
        .quodlibet/dumps
        .qt
        .recently-used.xbel
        .redhat
        .repoconfig
        .scala_history
        .sqlite_history
        .sunstudio
        .swt
        .terraform.d
        .texlive2020
        .texmf-var
        .themes
        .thumbnails
        .tmp
        .tooling
        .Trash
        .update-notifier
        .vidalia
        .wireshark
        .yarn
    )
    homedir_files=(
        .AndroidStudio2.0/config/options/feature.usage.statistics.xml
        .AndroidStudio2.0/config/options/statistics.application.usages.xml
        .AndroidStudio2.0/config/options/usage.statistics.xml
        .ICEauthority
        .aspell*
        .babel.json
        .cuda-gdbinit
        .emulator_console_auth_token
        .esd_auth
        .fixmyserver-homedir-write-test
        .fonts.conf
        .gnuplot_history
        .google-cookie
        .gtk-bookmarks
        .history
        .hivehistory
        .hphpd.history
        .hphpd.ini
        .imsettings.log
        .lesshst
        .mycli.log
        .myclirc
        .mysql_history
        .node_repl_history
        .ophcrackrc
        .pEp_management.db
        .pEp_management.db-shm
        .pEp_management.db-wal
        .pspg_history
        .pulse-cookie
        .recently-used
        .rediscli_history
        .repo_.gitconfig.json
        .rnd
        .scala_history
        .scm.sqlite
        .scuba_history
        .serfcli2
        .sqlite_history
        .sudo_as_admin_successful
        .tilp
        .v8flags*
        .vim/.netrwhist
        .viminfo
        .wget-hsts
        .xfce4-session.verbose-log*
        .xsession-errors*
        .xsettingsd
        .yarnrc
        .ypp_42
        .zcompdump
    )
    config_dirs=(
        abrt
        "chromium/Default/Local Storage"
        cinnamon-session
        clipit
        configstore
        coc/extensions/coc-java-data
        DjVuLibre
        enchant
        eog
        evince
        evolution
        filezilla
        gedit
        gnome-disk-utility
        gnome-initial-setup-done
        gnome-session
        goa-1.0
        "google-chrome/Default/Local Storage"
        google-googletalkplugin
        gtk-2.0
        gtk-3.0
        guvcview2
        htop
        ibus
        imsettings
        kazam
        lftp
        libreoffice
        libvirt
        menus
        nautilus
        octave
        procps
        qvm-mru-filecopy
        Skype
        "spotify/User Data"
        sqlitebrowser
        totem
        Thunar
        tracker
        viewnior
        wireshark
        xarchiver
        yelp
    )
    config_files=(
        QtProject.conf
        Trolltech.conf
        user-dirs.dirs
        user-dirs.locale
    )
    localshare_dirs=(
        gvfs-metadata
        lftp
        nautilus
        nvim
        tracker
        vlc
        xorg
    )
    tmpfiles=(
        com.apple.CoreSimulator.SimDevice.*
        com.apple.launchd.*
        fastzip-castree-uid-*
        gnash-cookies.*
        hhvm_*
        packman-fb-*
        par_preload_unpack.*
        par_unpack.*
        perf-*.map
        pymp-*
        scm-internal-stats*
        testpilot.*
        tmp*
        wmlock-*
        www-vmtouch-*
        www_vmtouch_db_cache.json
        com.apple.launchd.*
    )

    # separately to avoid any array issues
    #rm -rf $HOME/.android/!(avd)

    for d in "${homedir_dirs[@]}"; do
        rm -rf "$HOME/${d}"
    done
    for f in "${homedir_files[@]}"; do
        rm -f "$HOME/${f}"
    done
    for d in "${config_dirs[@]}"; do
        rm -rf "$HOME/.config/${d}"
    done
    for f in "${config_files[@]}"; do
        rm -f "$HOME/.config/${f}"
    done
    for d in "${localshare_dirs[@]}"; do
        rm -rf "$HOME/.local/share/${d}"
    done
    for d in "${tmpfiles[@]}"; do
        rm -rf /tmp/${tmpfiles} 2>/dev/null
    done
    rm -f $(locate recently-used.xbel)
    #locate '~' | grep '~$' | xargs -I% mv % ~/references/recovered_files

    # firefox trash
    cd $HOME/.mozilla 2>/dev/null
    rmdir extensions 2>/dev/null
    cd firefox 2>/dev/null
    for profile in $(ls -d *.default 2>/dev/null)
    do
      cd $profile
      rm -rf startupCache Cache bookmarkbackups thumbnails OfflineCache thumbnails
      rm -f adblockplus/patterns-backup* adblockplus/cache.js chromeappstore.sqlite
      cd ..
    done

    # clean up all docker shit
    if [ ! -z $(which docker 2>/dev/null) ]; then
      docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /etc:/etc spotify/docker-gc
    fi
    if [ $# -eq 1 ] && [ $1 == "-b" ]; then
      bleachbit_func
    fi
    root_func
}

function bleachbit_func ()
{
    if [ ! -z $(which bleachbit 2>/dev/null) ]; then
        bleachbit  -c \
            adobe_reader.cache \
            adobe_reader.mru \
            adobe_reader.tmp \
            amsn.cache \
            amule.logs \
            amule.tmp \
            apt.autoclean \
            apt.autoremove \
            audacious.cache \
            audacious.log \
            audacious.mru \
            beagle.cache \
            beagle.index \
            beagle.logs \
            chromium.cache \
            chromium.cookies \
            chromium.dom \
            chromium.form_history \
            chromium.vacuum \
            d4x.history \
            deepscan.ds_store \
            deepscan.thumbs_db \
            deepscan.tmp \
            easytag.logs \
            elinks.history \
            emesene.cache \
            emesene.logs \
            epiphany.cache \
            epiphany.cookies \
            epiphany.passwords \
            epiphany.places \
            evolution.cache \
            exaile.cache \
            exaile.downloaded_podcasts \
            exaile.log \
            filezilla.mru \
            firefox.cache \
            firefox.crash_reports \
            firefox.dom \
            firefox.forms \
            firefox.vacuum \
            flash.cache \
            flash.cookies \
            gedit.recent_documents \
            gftp.cache \
            gftp.logs \
            gimp.tmp \
            gl-117.debug_logs \
            gnome.run \
            gnome.search_history \
            google_chrome.cache \
            google_chrome.cookies \
            google_chrome.dom \
            google_chrome.form_history \
            google_chrome.history \
            google_chrome.passwords \
            google_chrome.search_engines \
            google_chrome.session \
            google_chrome.vacuum \
            google_earth.temporary_files \
            google_toolbar.search_history \
            gpodder.cache \
            gpodder.vacuum \
            gwenview.recent_documents \
            hippo_opensim_viewer.cache \
            hippo_opensim_viewer.logs \
            java.cache \
            kde.cache \
            kde.recent_documents \
            kde.tmp \
            konqueror.cookies \
            konqueror.current_session \
            konqueror.url_history \
            libreoffice.cache \
            libreoffice.history \
            liferea.cache \
            liferea.cookies \
            liferea.vacuum \
            links2.history \
            midnightcommander.history \
            miro.cache \
            miro.logs \
            nautilus.history \
            nexuiz.cache \
            octave.history \
            openofficeorg.cache \
            openofficeorg.recent_documents \
            opera.cache \
            opera.cookies \
            opera.current_session \
            opera.dom \
            opera.download_history \
            opera.search_history \
            opera.url_history \
            pidgin.cache \
            pidgin.logs \
            realplayer.cookies \
            realplayer.history \
            realplayer.logs \
            recoll.index \
            rhythmbox.cache \
            screenlets.logs \
            seamonkey.cache \
            seamonkey.chat_logs \
            seamonkey.cookies \
            seamonkey.download_history \
            seamonkey.history \
            secondlife_viewer.Cache \
            secondlife_viewer.Logs \
            sqlite3.history \
            system.custom \
            system.desktop_entry \
            system.localizations \
            system.recent_documents \
            system.rotated_logs \
            system.trash \
            thumbnails.cache \
            thunderbird.cache \
            thunderbird.cookies \
            thunderbird.vacuum \
            tremulous.cache \
            vim.history \
            vlc.mru \
            vuze.backup_files \
            vuze.cache \
            vuze.logs \
            vuze.tmp \
            warzone2100.logs \
            wine.tmp \
            winetricks.temporary_files \
            x11.debug_logs \
            xine.cache \
            yum.clean_all \
            yum.vacuum
      else
        echo "bleachbit not found in \$PATH" >&2
      fi
}

function root_func ()
{
    if [ $EUID == 0 ]; then
        echo LoL
#        rm -r "/usr/share/locale/{[a-dg-z]*,e!(n),fr[a-z_@]*}"
#        rm -r /usr/share/man/[a-no-z]*
    fi
}

if [ "${BASH_SOURCE[0]}" == "$0" ]; then
    main "$@"
fi
