#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
browser built-in downloaders can choke on large files, this script will convert
the curl command from 'browser devtools -> network -> copy as cURL' into an
aria2c command and run it

Usage:
    curl2aria [OPTION...] <PASTE CURL COMMAND HERE>
"""

import argparse
import logging
import re
import os
from typing import Tuple, List

LOG = logging.getLogger()
LOG.setLevel("INFO")
formatter: logging.Formatter = logging.Formatter("%(asctime)s - %(levelname)s - %(message)s")
ch: logging.StreamHandler = logging.StreamHandler()
ch.setFormatter(formatter)
LOG.addHandler(ch)


def parse_args() -> Tuple[argparse.Namespace, List[str]]:
    parser: argparse.ArgumentParser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="enable debug logging information",
    )
    parser.add_argument(
        "--norun",
        action="store_true",
        help="don't run the command, just print it to stdout"
    )
    return parser.parse_known_args()


def main() -> int:
    args, unknowns = parse_args()

    filter_re: re.Pattern[str] = re.compile("^(curl|--compressed)$")
    replace_header_re: re.Pattern[str] = re.compile(r"^range:\s*bytes=\d+-$")
    aria_cmd_list: List[str] = [
        "aria2c",
        "-x10",
        "-s20",
        "-m0",
    ]

    arg: str
    for arg in unknowns:
        if not filter_re.match(arg) and not replace_header_re.match(arg):
            if arg == "-H":
                arg = "--header"
            aria_cmd_list.append(f"'{arg}'")
    print("===========================")
    cmd: str = " ".join(aria_cmd_list)
    if args.norun:
        print(" ".join(aria_cmd_list))
    else:
        ret: int = os.system(cmd)
        return ret
    return 0


if __name__ == "__main__":
    main()
