#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Write_description_and_usage_example_here
"""

import argparse
import logging
import re

LOG = logging.getLogger()
LOG.setLevel("INFO")
formatter = logging.Formatter("%(asctime)s - %(levelname)s - %(message)s")
ch = logging.StreamHandler()
ch.setFormatter(formatter)
LOG.addHandler(ch)


def parse_args():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "-d", "--debug",
        action="store_true",
        help="enable debug logging information",
    )
    return parser.parse_known_args()


def main():
    args, unknowns = parse_args()

    filter_re = re.compile("^(curl|--compressed)$")
    replace_header_re = re.compile("^range:\s*bytes=\d+-$")
    aria_cmd_list = [
        "aria2c",
        "-x10",
        "-s20",
        "-m0",
    ]
    for arg in unknowns:
        if not filter_re.match(arg):
            if replace_header_re.match(arg):
                arg = "random_header: foobar"
            elif arg == "-H":
                arg = "--header"
            aria_cmd_list.append(f"'{arg}'")
    print("===========================")
    print(" ".join(aria_cmd_list))


if __name__ == "__main__":
    main()
