#!/usr/bin/env bash

# write some cool doc here

function main () {
    while getopts "h" opt; do
        case ${opt} in
            h)    # help message
                cat << EOF
Usage: $(basename $0) [OPTION]...
Options: -h: show this help dialog
EOF
                exit 0
                ;;
            ?)
                echo "Unknown option, exiting now" >&2
                exit 1
                ;;
        esac
    done
    sudo port selfupdate
    sudo port upgrade outdated
    sudo port uninstall leaves
    sudo port uninstall inactive
}

if [ "${BASH_SOURCE[0]}" == "$0" ]; then
    main "$@"
fi
