#!/bin/bash

function main() {
	if [ $# == 0 ]; then
		echo "Usage: $(basename $0) start|stop|show"
		exit 0
	elif [ $1 == start ]; then
		sudo service netfilter-persistent start
	elif [ $1 == stop ]; then
		sudo iptables -F
		sudo iptables -X
		sudo iptables -P INPUT ACCEPT
		sudo iptables -P OUTPUT ACCEPT
		#sudo iptables -P FORWARD ACCEPT
	elif [ $1 == show ]; then
		sudo iptables -L
	else
		echo "Usage: $(basename $0) start|stop|show"
	fi
}

if [ "${BASH_SOURCE[0]}" == "$0" ]; then
	main "$@"
fi
