#!/bin/bash

# updates all git repos in directory

function main ()
{
	GITARGS=${@:-pull}
	JOBOX_DIR=${JOBOX:-$HOME/Documents/jobox-src}

	cd "${JOBOX_DIR}"
	for subdir in *; do
		test -d "${subdir}/.git" || continue
		cd "${subdir}"
		repostatus=$(git st --short)
		if [ -z "${repostatus}" ]; then
			echo "=========== UPDATING REPO ${subdir} ==========="
			git ${GITARGS}
		else
			echo -e "\033[31m=========== DIRTY REPO $subdir ==========\033[0m"
		fi
		cd "${JOBOX_DIR}"
	done
}

if [ "${BASH_SOURCE[0]}" == "$0" ]; then
    main "$@"
fi
