#!/usr/bin/env bash

# display stats for a file in git source control

function usage()
{
    cat >&2 << EOF
Usage: ${0##*/} [OPTION]... FILE...
Options: -t N: display top N commits
         -h: show this help dialog
EOF
}

function filestats()
{
    filepath="${1}"
    shift

    if [ -d "${filepath}" ]; then
        txt="$(git ls-files "${filepath}" | xargs -rn1 git blame --date=format:%G --show-email --)"
    else
        txt="$(git blame --date=format:%G --show-email "${filepath}")"
    fi

    numlines="$(wc -l <<< "${txt}")"
    echo "${numlines} total lines" | sed 's/^\s+//'
    echo "----- YEARS -----"
    grep -oE '\(<.*@[^>]*>\s+[0-9]{4}\s+[0-9]*\)' <<< "${txt}" \
        | sed 's/^(.*\([0-9]\{4\}\).*)$/\1/' \
        | sort \
        | uniq -c \
        | sort -r \
        | awk '{print $2 " -> " $1 " lines"}'
    echo "----- TOP AUTHORS -----"
    grep -oE '\(<.*@[^>]*>\s+[0-9]{4}\s+[0-9]*\)' <<< "${txt}" \
        | sed 's/^(\(<.*@.*>\).*)$/\1/' \
        | sort \
        | uniq -c \
        | sort -r \
        | head -n"${TOP}" \
        | awk '{print $2 " -> " $1 " lines"}' | column -t
    echo "----- TOP DIFFS -----"
    cut -b-8 <<< "${txt}" \
        | sort \
        | uniq -c \
        | sort -rn \
        | head -n"${TOP}" \
        | awk '{print $2}' \
        | grep -v '00000000' \
        | xargs -n1 git log -n1 --pretty='%h %ai %aE		%s'
}

function main()
{
    TOP=5
    while getopts "t:h" opt; do
        case ${opt} in
            h) # help message
                usage
                exit 0
                ;;
            t)
                TOP="${OPTARG}"
                shift
                shift
                ;;
            ?)
                echo "Unknown option, exiting now" >&2
                exit 1
                ;;
        esac
    done

    if [ $# -eq 0 ]; then
        usage
        exit 1
    fi

    for file in "${@}"; do
        printf "============= %s =============\n" "${file}"
        filestats "${file}"
    done
}

if [ "${BASH_SOURCE[0]}" == "$0" ]; then
    main "$@"
fi
