#!/usr/bin/env perl

use strict;
use warnings;

use WWW::Mechanize ;
use URI;
use URI::QueryParam;

sub main {
    my $mech = new WWW::Mechanize;
    my $google = 'https://www.google.com/search?q=';
    my $keywords = join "%20", @ARGV;

    $mech->get( $google . $keywords );
    foreach my $link ( $mech->links() ) {
        my $google_url = $link->url;
        if ( $google_url =~ /\/url\?q=/ ) {
            print URI->new($google_url)->query_param("q") . "\n";
        }
    }
}

main();
