#!/bin/bash

#

function main ()
{
	if [ $# != 1 ]; then
		echo "Usage: $0 FILENAME"
		exit 1
	fi
	filename="${1}"; shift
	sed -i '' -e 's/^[”“"]//' "${filename}"
	sed -i '' -e 's/\\//g' "${filename}"
	sed -i '' -e 's/[”“]/"/g' "${filename}"
	cat "${filename}" | jq
}

if [ "${BASH_SOURCE[0]}" == "$0" ]; then
    main "$@"
fi
