#!/bin/bash

#

function main ()
{
	if [ $# != 1 ]; then
		echo "Usage: $0 FILENAME"
		exit 1
	fi
	filename="${1}"; shift
	sed -e 's/^[”“"]//' "${filename}" | \
	    sed -e 's/\\//g' | \
	    sed -e 's/[”“]/"/g' | \
	    jq
}

if [ "${BASH_SOURCE[0]}" == "$0" ]; then
    main "$@"
fi
