#!/usr/bin/env bash

#

function main ()
{
    if [ $# != 1 ]; then
        echo "Usage: $0 FILENAME"
        exit 1
    fi
    filename="${1}"; shift
    sed -E 's/^[”“"]//g;s/\\//g;s/[”“]/"/g;s/=/:/g;s/;\s*/,/g' "${filename}" | \
        sed -E ':a;{N;s/\n//;ba}' | \
        sed -E 's/\s+/ /g;s/,\s*([}]?)/\1/g;s/([^\w])(\w+)([^\w])/\1"\2"\3/g' #"${filename}" #| jq
}

if [ "${BASH_SOURCE[0]}" == "$0" ]; then
    main "$@"
fi
