#!/usr/bin/env -S bash

set -e -u
set -o pipefail

# write some cool doc here

function usage()
{
    cat << EOF
Usage: ${0##*/}" [OPTION] ACTION QUERY
Options: --help, -h: show this help dialog
         -n NUM: number of results to show
Actions:
    search: search pypi for packages named QUERY
    show: display info on package QUERY
EOF
}

function pypi_search()
{
    readonly PAGESIZE=20
    query="${1}"
    shift
    NUM="${1:-$PAGESIZE}"
    n=0

    while [ "${n}" -lt "${NUM}" ]; do
        pageno="$(("${n}" / "${PAGESIZE}" + 1))"
        n="$(("${n}" + "${PAGESIZE}"))"
        webpage="$(curl -s "https://pypi.org/search/?q=${query}&page=${pageno}" \
            -H 'Accept-Encoding: gzip, deflate, br' \
            | gzip -d)"
        package_names="$(xmllint --html --xpath '//span[@class = "package-snippet__name"]/text()' - <<< "${webpage}" 2> /dev/null)"
        package_versions="$(xmllint --html --xpath '//span[@class = "package-snippet__version"]/text()' - <<< "${webpage}" 2> /dev/null)"
        package_releasedate="$(xmllint --html --xpath '//span[@class = "package-snippet__released"]//text()' - <<< "${webpage}" 2> /dev/null | sed '/^$/d')"
        package_desc="$(xmllint --html --xpath '//p[@class = "package-snippet__description"]/text()' - <<< "${webpage}" 2> /dev/null)"
        paste <(echo "${package_names}") <(echo "${package_versions}") <(echo "${package_releasedate}") <(echo "${package_desc}")
    done
}

function pypi_show()
{
    printf 'Implement me!\n'
}

function main()
{
    NUM=20

    while getopts "hn:-:" opt; do
        case ${opt} in
            h) # help message
                usage
                exit 0
                ;;
            n)
                NUM="${OPTARG}"
                ;;
            -)
                case "${OPTARG}" in
                    help)
                        usage
                        exit 0
                        ;;
                    *)
                        printf 'Unknown option, exiting now\n' >&2
                        exit 1
                        ;;
                esac
                ;;
            ?)
                printf 'Unknown option, exiting now\n' >&2
                exit 1
                ;;
        esac
    done
    shift $((OPTIND - 1))
    [[ ${1:-} == '--' ]] && shift

    action="${1}"
    shift
    query="${1}"
    shift

    case "${action}" in
        search)
            pypi_search "${query}" "${NUM}"
            ;;
        show)
            pypi_show "${query}"
            ;;
        *)
            printf 'Unknown action, exiting now\n' >&2
            exit 1
            ;;
    esac
}

if [ "${BASH_SOURCE[0]}" == "$0" ]; then
    main "$@"
fi
