#!/usr/bin/env bash

set -e -u
set -o pipefail

function main ()
{
    local dirname=$(mktemp -d);
    sudo chown "${USER}:${USER}" "${dirname}"
    chmod 700 "${dirname}"
    echo $dirname
    read -p "ready to continue? "
    sudo mount -t tmpfs tmpfs "${dirname}";
    cd "${dirname}";
    local COPYFILES=(
        .bashrc
        .config/bash
        .config/tmux
        .inputrc
        .profile
        .tmux.conf
        .vim
    )
    for f in "${COPYFILES[@]}"; do
        dir="$(dirname "${f}")"
        file="${f##*/}"
        test -e ~/"${f}"&& \
            mkdir -p "${dirname}/${dir}" && \
            cp -rv ~/"${f}" "${dirname}/${dir}/"
    done
    ln -s ~/bin "${dirname}";
    HOME="${dirname}" bash;
    rm -f "${dirname}/bin"
    find -P "${dirname}" -type f -print0 | xargs -r0 shred -zfu;
    cd -;
    sudo rm -rf "${dirname}/*";
    sudo umount "${dirname}";
    rmdir "${dirname}"
}

if [ "${BASH_SOURCE[0]}" == "$0" ]; then
    main "$@"
fi
