#!/usr/bin/env bash

function main()
{
    pkill Spotify
    #sudo "$(which sat)"
    sleep 2
    open -ga Spotify
    sleep 3
    osascript -e 'tell application "spotify" to play'
    #sleep 2
    #sudo "$(which sat)"
}

if [ "${BASH_SOURCE[0]}" == "$0" ]; then
    main "$@"
fi
