#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import getopt
import sys

def usage() -> None:
    sys.stderr.write(
"""Usage: {} [-d DELIM]\n""".format(sys.argv[0])
)

def main() -> None:
    delim: str = '\t'
    try:
        opts, args = getopt.getopt(sys.argv[1:], 'd:h', ['delimiter='])
    except getopt.GetoptError:
        usage()
        sys.exit(2)

    for opt, arg in opts:
        if opt in ('-h', '--help'):
            usage()
            sys.exit(0)
        elif opt in ('-d', '--delimiter'):
            delim = arg
        else:
            usage()
            sys.exit(1)

    for line in sys.stdin:
        for segment in line.strip().split(delim):
            print(segment)

if __name__ == '__main__':
    main()
