#!/bin/bash

# download host lists and apply them to /etc/hosts
# this should be sufficient to kill ads in both spotify and google play

function enable ()
{
    case $(uname) in
        Linux)
            GROUP=root
            ;;
        Darwin)
            GROUP=wheel
            ;;
    esac

    # backup hosts file if there is none
    if [ ! -e /etc/hosts.orig ]; then
        sudo cp /etc/hosts{,.orig}
        read -r -d '' textstr << EOM

# The following hosts are all ad servers, the list can be updated by
# running update_hosts

127.0.0.1   gads.pubmatic.com
127.0.0.1   spclient.wg.spotify.com
EOM
            sudo tee -a /etc/hosts.orig > /dev/null <<< "${textstr}"
    fi
    # whitelist exactly the hostname pattern here. "^mixpanel.com$" will
    # whitelist traffic to mixpanel.com, but lines such as
    # api.mixpanel.com will still be blocked
    whitelist=(
        "^mixpanel.com$"
        "^www.mixpanel.com$"
        "^segment.com$"
        "^airbrake.io$"
        "^www.inmobi.com$"
    )

    adservers="
        https://adaway.org/hosts.txt
        https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
    "
    newhosts=$(mktemp)

    # remove lines with localhost, we already take care of those
    # make sure only lines redirecting to localhost are authorized
    # convert from that BS that windows calls EOLs to proper '\n's
    # strip inline comments and replace tabs with spaces
    # replace space following ipaddr with a tab for consistency
    # remove duplicate lines
    curl ${adservers}  \
        | grep -v localhost \
        | sed -nE '/^(127\.0\.0\.1|::1)[[:space:]]+/p' \
        | dos2unix \
        | sed -E 's/[[:space:]]+#.*//;s/^(127\.0\.0\.1|::1) +/\1    /;s/\t/    /g' \
        | awk '!seen[$0]++' \
        > "${newhosts}"
    # remove whitelisted lines
    for w in ${whitelist[@]}; do
        pattern="$(sed 's/\^/^127.0.0.1    /' <<< "${w}")"
        sed -i "/${pattern}/d"  "${newhosts}"
    done
    cat /etc/hosts.orig | sudo tee /etc/hosts > /dev/null
    cat "${newhosts}" | sudo tee -a /etc/hosts > /dev/null
    sudo chown "root:${GROUP}" /etc/hosts
    sudo chmod 644 /etc/hosts
    rm "${newhosts}"
}


function disable ()
{
    sudo cp /etc/hosts{.orig,}
}


function usage ()
{
    cat << EOM
Usage: $0 [--enable|--disable]
    --enable: enable ad-blocking
    --disable: disable ad-blocking
EOM
}


function main ()
{
    local action="${1##--}"
    test -z $action && action=enable

    while getopts "h-:" opt; do
        case ${opt} in
            h)  # help message
                usage
                exit 0
                ;;
            -)
                case "${OPTARG}" in
                    help)
                        usage
                        exit 0
                        ;;
                    enable)
                        action=enable
                        ;;
                    disable)
                        action=disable
                        ;;
                    *)
                        printf 'Unknown option, exiting now\n' >&2
                        exit 1
                        ;;
                esac
                ;;
            ?)
                printf 'Unknown option, exiting now\n' >&2
                exit 1
                ;;
        esac
    done
    shift $((OPTIND - 1))
    [[ "${1:-}" == '--' ]] && shift

    case "${action}" in
        enable)
            enable
            ;;
        disable)
            disable
            ;;
        *)
            printf "programming error: missing case statement\n" >&2
            ;;
    esac
}

if [ "${BASH_SOURCE[0]}" == "$0" ]; then
    main "$@"
fi
