#!/bin/bash -e

# From https://www.facebook.com/groups/hack.of.the.day/permalink/1373649706016974/

function main ()
{
    tzs=(
        Current
        America/Chicago
        America/New_York
        Asia/Singapore
        Asia/Tel_Aviv
        Europe/London
        Europe/Paris
    )

    max_tz_len() {
        max=0
        for tz in "${tzs[@]}"; do
            cur=${#tz}
            (( cur > max )) && max=$cur
        done
        echo "$max"
    }

    len=$(max_tz_len)
    for tz in "${tzs[@]}"; do
        printf "%${len}s: " "$tz"

        if [[ $tz == Current ]]; then
            date
        else
            TZ="$tz" date
        fi
    done
}

if [ "${BASH_SOURCE[0]}" == "$0" ]; then
    main "$@"
fi
