#!/usr/bin/env bash

set -eu
set -o pipefail

# From https://www.facebook.com/groups/hack.of.the.day/permalink/1373649706016974/

function max_tz_len()
{
    max=0
    for tz in "${tzs[@]}"; do
        cur=${#tz}
        ((cur > max)) && max=$cur
    done
    echo "$max"
}

function main()
{
    if [ $# -ge 1 ]; then
        dateparam="${*}"
    else
        dateparam=""
    fi

    tzs=(
        Current
        America/Los_Angeles
        America/Chicago
        America/New_York
        Europe/Paris
        Europe/Warsaw
        Asia/Kolkata
        Asia/Tel_Aviv
        UTC
    )

    len=$(max_tz_len)
    for tz in "${tzs[@]}"; do
        printf "%${len}s: " "$tz"

        if [[ $tz == Current ]]; then
            if [ -n "${dateparam}" ]; then
                date "+%a %Y-%m-%d %T %z" "${dateparam}"
            else
                date "+%a %Y-%m-%d %T %z"
            fi
        else
            if [ -n "${dateparam}" ]; then
                TZ="${tz}" date "+%a %Y-%m-%d %T %z" "${dateparam}"
            else
                TZ="$tz" date "+%a %Y-%m-%d %T %z"
            fi
        fi
    done
}

if [ "${BASH_SOURCE[0]}" == "$0" ]; then
    main "$*"
fi
