#!/usr/bin/env -S bash

# reaps zombie processes

set -e -u
set -o pipefail

function main()
{
    #ps -A|grep -E '\b[zZ]\b'|awk '{print $2}'|tee|xargs -r kill

    # shellcheck disable=SC2009
    processes=$(ps aux | grep -E '\s+[zZ]\s+')
    if [ -n "${processes}" ]; then
        echo "Killing:"
        echo "${processes}"
        pids="$(awk '{print $2}' <<< "${processes}")"
        sleep .1 # don't bother with short lived processes
        echo "${pids}" | xargs -r kill
    else
        echo "No zombie processes!"
    fi
}

if [ "${BASH_SOURCE[0]}" == "$0" ]; then
    main "$@"
fi
