#!/usr/bin/env -S bash

# write some cool doc here

if [ -n "${DEBUG}" ]; then
    exec 5> /tmp/bash_debug_output.txt
    BASH_XTRACEFD="5"
    PS4='$LINENO: '
    set -x -T
fi
set -e -u
set -o pipefail

function usage()
{
    cat << EOF
Usage: ${0##*/}" [OPTION]...
Options: --help, -h: show this help dialog
         --nobell: don't ring bell once done
EOF
}

function main()
{
    bell=true

    while getopts "h-:" opt; do
        case ${opt} in
            h) # help message
                usage
                exit 0
                ;;
            -)
                case "${OPTARG}" in
                    help)
                        usage
                        exit 0
                        ;;
                    nobell)
                        bell=false
                        ;;
                    *)
                        printf 'Unknown option, exiting now\n' >&2
                        exit 1
                        ;;
                esac
                ;;
            ?)
                printf 'Unknown option, exiting now\n' >&2
                exit 1
                ;;
        esac
    done
    shift $((OPTIND - 1))
    [[ ${1:-} == '--' ]] && shift

    curl -X POST -s 'https://free.churchless.tech/v1/chat/completions' \
        -H 'Content-Type: application/json' \
        -d "{\"messages\":[{\"role\": \"user\", \"content\": \"${*}\"}]}" \
        | jq -r '.choices[].message.content' \
        | xargs -0 echo -e

    if "${bell}"; then
        bell
    fi
}

if [ "${BASH_SOURCE[0]}" == "$0" ]; then
    main "$@"
fi
