#!/usr/bin/env bash

# set up all binaries to use firejail profiles as default everywhere

function main ()
{
	for profile in /etc/firejail/*; do
		binary_name="$(basename "${profile%\.profile}")"
		path=$(which "${binary_name}")
		if [ ! -z "${path}" ]; then
			echo "${binary_name}"
		fi
	done
}

if [ "${BASH_SOURCE[0]}" == "$0" ]; then
    main "$@"
fi
