#!/system/bin/env bash

set -e -u
set -o pipefail

# wrapper around `borgbackup` to make sure it runs with all the correct params
#
# Usecase: use cron to auto-backup `/storage/emulated/$user` every night. You
# will need a rooted phone with a microsd slot and a microsd card of large
# enough size
# - install https://f-droid.org/en/packages/it.faerb.crond/
# - install https://f-droid.org/en/packages/com.termux/
# - launch termux, install borgbackup and jq
# - make sure your miscro-sd card is mounted on the phone, see
#   https://github.com/jrabinow/homedir-scripts/blob/main/platform_specific/android/luksmount
# - save https://github.com/jrabinow/droidscripts/blob/main/termux_cronwrap.sh to
#   `/data` and `chmod +x` it
# - add `/data/termux_cronwrap.sh cronenborg -u0` to your /data/crontab to
#   backup user0's internal storage to the phone's microsd card
# - optional: install termux:api from fdroid for notifications


readonly PARTLABEL=microsd_luks
readonly PARTUUID="$(blkid "/dev/mapper/${PARTLABEL}" -o export|grep '^UUID'|cut -d= -f2)"
readonly REPO_PATH="/mnt/media_rw/${PARTUUID}/archive"
readonly BATT_MIN_PERCENTAGE=30

function usage()
{
    cat << EOF
Usage: ${0##*/}" [OPTION]...
Options: --help, -h: show this help dialog
EOF
}

function battery_status ()
{
    battstats=$(termux-battery-status)
    isplugged="$(jq -r .plugged <<< "${battstats}")"
    percentage="$(jq -r .percentage <<< "${battstats}")"

    [ "${isplugged}" == "PLUGGED" ] || [ "${percentage}" -ge ${BATT_MIN_PERCENTAGE} ]
}

function main()
{
    user=0
    while getopts "hu:-:" opt; do
        case ${opt} in
            h) # help message
                usage
                exit 0
                ;;
            u)
                user="${OPTARG}"
                ;;
            -)
                case "${OPTARG}" in
                    help)
                        usage
                        exit 0
                        ;;
                    *)
                        printf 'Unknown option, exiting now\n' >&2
                        exit 1
                        ;;
                esac
                ;;
            ?)
                printf 'Unknown option, exiting now\n' >&2
                exit 1
                ;;
        esac
    done
    shift $((OPTIND - 1))
    [[ ${1:-} == '--' ]] && shift

    archive_ts="$(date +"%Y-%m-%d-%H-%M-%S")"
    archive_name="u${user}_storage_${archive_ts}"
    full_repo_path="${REPO_PATH}/${user}/storage.borg"
    full_archive_path="${full_repo_path}::${archive_name}"

    if battery_status; then
        if [ ! -d "${full_repo_path}" ]; then
            mkdir -p "${full_repo_path}"
            borg init "${full_repo_path}"
        fi
        borg create -e Android "${full_archive_path}" "/storage/emulated/${user}"
        borg prune --keep-last 1 --keep-minutely 60 -H 24 -d 7 -w 4 -m 12 -y 10 "${full_repo_path}"
        if command -v termux-notification > /dev/null; then
            termux-notification -t "cronenborg" -c "${archive_name} successfully created for user ${user}"
        fi
    elif command -v termux-notification > /dev/null; then
        termux-notification -t "cronenborg" -c "battery not charging and too low, skipping for user ${user}"
    fi
}

if [ "${BASH_SOURCE[0]}" == "$0" ]; then
    main "$@"
fi
