#!/system/bin/env bash

set -e -u
set -o pipefail

# write some cool doc here
readonly PARTLABEL=microsd_luks
readonly PARTUUID="$(blkid "/dev/mapper/${PARTLABEL}" -o export|grep '^UUID'|cut -d= -f2)"
readonly REPO_PATH="/mnt/media_rw/${PARTUUID}/archive"

function usage()
{
    cat << EOF
Usage: ${0##*/}" [OPTION]...
Options: --help, -h: show this help dialog
EOF
}

function battery_status ()
{
    battstats=$(termux-battery-status)
    isplugged="$(jq -r .plugged <<< "${battstats}")"
    percentage="$(jq -r .percentage <<< "${battstats}")"

    [ "${isplugged}" == "PLUGGED" ] || [ "${percentage}" -ge 30 ]
}

function main()
{
    user=0
    while getopts "hu:-:" opt; do
        case ${opt} in
            h) # help message
                usage
                exit 0
                ;;
            u)
                user="${OPTARG}"
                ;;
            -)
                case "${OPTARG}" in
                    help)
                        usage
                        exit 0
                        ;;
                    *)
                        printf 'Unknown option, exiting now\n' >&2
                        exit 1
                        ;;
                esac
                ;;
            ?)
                printf 'Unknown option, exiting now\n' >&2
                exit 1
                ;;
        esac
    done
    shift $((OPTIND - 1))
    [[ ${1:-} == '--' ]] && shift

    archive_ts="$(date +"%Y-%m-%d-%H-%M-%S")"
    archive_name="u${user}_storage_${archive_ts}"
    full_repo_path="${REPO_PATH}/${user}/storage.borg"
    full_archive_path="${full_repo_path}::${archive_name}"

    if battery_status; then
        borg create -e Android "${full_archive_path}" "/storage/emulated/${user}"
        borg prune --keep-last 1 --keep-minutely 60 -H 24 -d 7 -w 4 -m 12 -y 10 "${full_repo_path}"
    fi
}

if [ "${BASH_SOURCE[0]}" == "$0" ]; then
    main "$@"
fi
