#!/system/bin/sh

# decrypt and mount luks-encrypted micro-sdcard to $MOUNTBASE
# Initial setup:
# https://github.com/jrabinow/droidscripts/blob/main/microsd/setup_microsd.sh
# Also correct the $PARTITION var if incorrect. MOUNTBASE can be adjusted to
# anything you want.
# Run as root in an environment with cryptsetup installed, easiest way I'm aware of
# is to install termux from fdroid and install cryptsetup from there.
#
# https://blog.ja-ke.tech/2020/04/04/android-luks2.html

PARTITION=/dev/block/mmcblk0p2
LABEL=microsd_luks
MOUNTBASE=/mnt/media_rw

set -e -u
set -o pipefail

function usage()
{
    cat << EOF
Usage: ${0##*/}" [OPTION]...
Options: --help, -h: show this help dialog
EOF
}

function main()
{
    while getopts "h-:" opt; do
        case ${opt} in
            h) # help message
                usage
                exit 0
                ;;
            -)
                case "${OPTARG}" in
                    help)
                        usage
                        exit 0
                        ;;
                    *)
                        printf 'Unknown option, exiting now\n' >&2
                        exit 1
                        ;;
                esac
                ;;
            ?)
                printf 'Unknown option, exiting now\n' >&2
                exit 1
                ;;
        esac
    done
    shift $((OPTIND - 1))
    [[ ${1:-} == '--' ]] && shift

    if [ $(id -u) != 0 ]; then
        echo "Aborting: This script needs root." >&2
        exit 1
    fi

    # Try to open container
    if [ ! -b "/dev/mapper/${LABEL}" ]; then
        cryptsetup luksOpen "${PARTITION}" "${LABEL}"
    else
        echo "Container already open, skipped cryptsetup..." >&2
    fi

    sdcard_uuid="$(blkid "/dev/mapper/${LABEL}" -o export|grep '^UUID='|cut -d= -f2)"
    TARGET="${MOUNTBASE}/${sdcard_uuid}"
    mkdir -p "${TARGET}"

    # Mounting
    nsenter -t 1 -m sh << EOF
mountpoint "${TARGET}" >/dev/null || mount -t ext4 -o nosuid,nodev,noatime "/dev/mapper/${LABEL}" "${TARGET}"
EOF
}

main "$@"
