---
- name: Spin up Instances
  hosts: localhost
  connection: local
  tasks:
   - name: Spin up Instances
     ec2:
       instance_type: t2.micro
       region: us-east-1
       group: default
       image: ami-9eaa1cf6
       key_name: jrabinow
       instance_tags:
         Name: "Remote server"
       exact_count: 1
       count_tag:
               Name: "Remote server"
       vpc_subnet_id: subnet-59ff2264
       assign_public_ip: yes
       wait: yes
     register: ec2
   - name: Wait for instance to be ready
     wait_for: host={{ item.public_ip }} port=22 delay=1 timeout=600 state=started
     with_items: ec2.instances
