---
- name: pull data from remote server
  hosts: ec2
  tasks:
    - stat: path="${{ dest }}"
      register: st
    - fetch: src="{{ src }}" dest="{{ dest }}" fail_on_missing=yes flat=yes
      when: not st.stat.exists
