---
- name: terminate all instances
  hosts: localhost
  connection: local
  tasks:
  - name: register instance data
    ec2_instances:
      region: 'us-east-1'
    register: ec2all
  - name: Terminate instances that were previously launched
    ec2:
      state: 'absent'
      region: 'us-east-1'
      instance_ids: '{{ ec2all.instance_ids }}'